
//
// 
//

import UIKit

public class Material3DesignKitCommunity {
    public static let contentStaticBodyLargeFont = "Roboto"
    public static let contentStaticBodyLargeWeight = "Regular"
    public static let contentStaticBodyLargeWeightEmphasized = "Medium"
    public static let contentStaticBodyMediumFont = "Roboto"
    public static let contentStaticBodyMediumWeight = "Regular"
    public static let contentStaticBodyMediumWeightEmphasized = "Medium"
    public static let contentStaticBodySmallFont = "Roboto"
    public static let contentStaticBodySmallWeight = "Regular"
    public static let contentStaticBodySmallWeightEmphasized = "Medium"
    public static let contentStaticDisplayLargeFont = "Roboto"
    public static let contentStaticDisplayLargeWeight = "Regular"
    public static let contentStaticDisplayLargeWeightEmphasized = "Medium"
    public static let contentStaticDisplayMediumFont = "Roboto"
    public static let contentStaticDisplayMediumWeight = "Regular"
    public static let contentStaticDisplayMediumWeightEmphasized = "Medium"
    public static let contentStaticDisplaySmallFont = "Roboto"
    public static let contentStaticDisplaySmallWeight = "Regular"
    public static let contentStaticDisplaySmallWeightEmphasized = "Medium"
    public static let contentStaticHeadlineLargeFont = "Roboto"
    public static let contentStaticHeadlineLargeWeight = "Regular"
    public static let contentStaticHeadlineLargeWeightEmphasized = "Medium"
    public static let contentStaticHeadlineMediumFont = "Roboto"
    public static let contentStaticHeadlineMediumWeight = "Regular"
    public static let contentStaticHeadlineMediumWeightEmphasized = "Medium"
    public static let contentStaticHeadlineSmallFont = "Roboto"
    public static let contentStaticHeadlineSmallWeight = "Regular"
    public static let contentStaticHeadlineSmallWeightEmphasized = "Medium"
    public static let contentStaticLabelLargeFont = "Roboto"
    public static let contentStaticLabelLargeWeight = "Medium"
    public static let contentStaticLabelLargeWeightEmphasized = "SemiBold"
    public static let contentStaticLabelMediumFont = "Roboto"
    public static let contentStaticLabelMediumWeight = "Medium"
    public static let contentStaticLabelMediumWeightEmphasized = "SemiBold"
    public static let contentStaticLabelSmallFont = "Roboto"
    public static let contentStaticLabelSmallWeight = "Medium"
    public static let contentStaticLabelSmallWeightEmphasized = "SemiBold"
    public static let contentStaticTitleLargeFont = "Roboto"
    public static let contentStaticTitleLargeWeight = "Regular"
    public static let contentStaticTitleLargeWeightEmphasized = "Medium"
    public static let contentStaticTitleMediumFont = "Roboto"
    public static let contentStaticTitleMediumWeight = "Medium"
    public static let contentStaticTitleMediumWeightEmphasized = "SemiBold"
    public static let contentStaticTitleSmallFont = "Roboto"
    public static let contentStaticTitleSmallWeight = "Medium"
    public static let contentStaticTitleSmallWeightEmphasized = "SemiBold"
}
